services:
  postgres:
    container_name: postgres
    image: postgres
    environment: 
      POSTGRES_DB: django-online-shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
    networks:
      - main
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn djangoonlineshop.wsgi -b 0.0.0.0:8001"
    volumes:
      - .:/web/
    depends_on:
      - postgres
    expose:
      - 8001
    ports:
      - "8001:8001"
    networks:
      - main
networks:
  main:
volumes:
  postgres_data:
