# Generated by Django 5.2.4 on 2025-07-31 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='total_price',
        ),
    ]
